// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;



public partial class tb_cargos
{
    [Key]
    public int car_id { get; set; }

    [Required]
    [StringLength(50)]
    
    public string car_nome { get; set; }

    [InverseProperty("mem_fk_car")]
    public virtual ICollection<tb_membros> tb_membros { get; set; } = new List<tb_membros>();
}