// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;



public partial class tb_despesas
{
    [Key]
    public int des_id { get; set; }

    [Required]
    [StringLength(50)]
    
    public string des_descricao { get; set; }

    [Column(TypeName = "decimal(10, 2)")]
    public decimal des_valor { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime des_data { get; set; }

    [StringLength(100)]
    
    public string des_observacao { get; set; }
}