// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;



public partial class tb_dizimos
{
    [Key]
    public int diz_id { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime diz_data { get; set; }

    [Column(TypeName = "decimal(10, 2)")]
    public decimal diz_valor { get; set; }

    public int diz_fk_mem_id { get; set; }

    [ForeignKey("diz_fk_mem_id")]
    [InverseProperty("tb_dizimos")]
    public virtual tb_membros diz_fk_mem { get; set; }
}