// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;



public partial class tb_membros
{
    [Key]
    public int mem_id { get; set; }

    [Required]
    [StringLength(50)]
    
    public string mem_nome { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime mem_data_cadastro { get; set; }

    public int? mem_fk_car_id { get; set; }

    public int? mem_fk_min_id { get; set; }

    public bool? mem_batizado { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? mem_data_batismo { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? mem_data_nascimento { get; set; }

    [StringLength(50)]
    
    public string mem_telefone { get; set; }

    [StringLength(50)]
    
    public string mem_email { get; set; }

    [StringLength(50)]
    
    public string mem_rua { get; set; }

    [StringLength(50)]
    
    public string mem_bairro { get; set; }

    [StringLength(50)]
    
    public string mem_numero { get; set; }

    [StringLength(50)]
    
    public string mem_cidade { get; set; }

    [StringLength(50)]
    
    public string mem_estado { get; set; }

    [ForeignKey("mem_fk_car_id")]
    [InverseProperty("tb_membros")]
    public virtual tb_cargos mem_fk_car { get; set; }

    [ForeignKey("mem_fk_min_id")]
    [InverseProperty("tb_membros")]
    public virtual tb_ministerios mem_fk_min { get; set; }

    [InverseProperty("diz_fk_mem")]
    public virtual ICollection<tb_dizimos> tb_dizimos { get; set; } = new List<tb_dizimos>();
}