// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;



public partial class tb_ministerios
{
    [Key]
    public int min_id { get; set; }

    [Required]
    [StringLength(50)]
    
    public string min_nome { get; set; }

    [StringLength(250)]
    
    public string min_descricao { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? min_data_criacao { get; set; }

    [InverseProperty("mem_fk_min")]
    public virtual ICollection<tb_membros> tb_membros { get; set; } = new List<tb_membros>();
}