// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;



public partial class tb_ofertas
{
    [Key]
    public int ofe_id { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime ofe_data { get; set; }

    [Required]
    [StringLength(50)]
    
    public string ofe_tipo_ferta { get; set; }
}