// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;



public partial class tb_usuarios
{
    [Key]
    public int usu_id { get; set; }

    [StringLength(50)]
    
    public string usu_nome { get; set; }

    [StringLength(50)]
    
    public string uso_login { get; set; }

    [StringLength(50)]
    
    public string uso_nome { get; set; }

    public int uso_fk_niv_id { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? uso_data { get; set; }

    [ForeignKey("uso_fk_niv_id")]
    [InverseProperty("tb_usuarios")]
    public virtual tb_nivel_acesso uso_fk_niv { get; set; }
}