//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace IpgaSystem.XPO.IpgaDB
{

    [Persistent(@"tb_cargos")]
    public partial class tb_cargosXPO : XPLiteObject
    {
        int fcar_id;
        [Key(true)]
        public int car_id
        {
            get { return fcar_id; }
            set { SetPropertyValue<int>(nameof(car_id), ref fcar_id, value); }
        }
        string fcar_nome;
        [Size(50)]
        public string car_nome
        {
            get { return fcar_nome; }
            set { SetPropertyValue<string>(nameof(car_nome), ref fcar_nome, value); }
        }
        [Association(@"tb_membrosXPOReferencestb_cargosXPO")]
        public XPCollection<tb_membrosXPO> tb_membross { get { return GetCollection<tb_membrosXPO>(nameof(tb_membross)); } }
    }

}
