//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace IpgaSystem.XPO.IpgaDB
{

    [Persistent(@"tb_membros")]
    public partial class tb_membrosXPO : XPLiteObject
    {
        int fmem_id;
        [Key(true)]
        public int mem_id
        {
            get { return fmem_id; }
            set { SetPropertyValue<int>(nameof(mem_id), ref fmem_id, value); }
        }
        string fmem_nome;
        [Size(50)]
        public string mem_nome
        {
            get { return fmem_nome; }
            set { SetPropertyValue<string>(nameof(mem_nome), ref fmem_nome, value); }
        }
        DateTime fmem_data_cadastro;
        public DateTime mem_data_cadastro
        {
            get { return fmem_data_cadastro; }
            set { SetPropertyValue<DateTime>(nameof(mem_data_cadastro), ref fmem_data_cadastro, value); }
        }
        tb_cargosXPO fmem_fk_car_id;
        [Association(@"tb_membrosXPOReferencestb_cargosXPO")]
        public tb_cargosXPO mem_fk_car_id
        {
            get { return fmem_fk_car_id; }
            set { SetPropertyValue<tb_cargosXPO>(nameof(mem_fk_car_id), ref fmem_fk_car_id, value); }
        }
        tb_ministeriosXPO fmem_fk_min_id;
        [Association(@"tb_membrosXPOReferencestb_ministeriosXPO")]
        public tb_ministeriosXPO mem_fk_min_id
        {
            get { return fmem_fk_min_id; }
            set { SetPropertyValue<tb_ministeriosXPO>(nameof(mem_fk_min_id), ref fmem_fk_min_id, value); }
        }
        bool fmem_batizado;
        public bool mem_batizado
        {
            get { return fmem_batizado; }
            set { SetPropertyValue<bool>(nameof(mem_batizado), ref fmem_batizado, value); }
        }
        DateTime fmem_data_batismo;
        public DateTime mem_data_batismo
        {
            get { return fmem_data_batismo; }
            set { SetPropertyValue<DateTime>(nameof(mem_data_batismo), ref fmem_data_batismo, value); }
        }
        DateTime fmem_data_nascimento;
        public DateTime mem_data_nascimento
        {
            get { return fmem_data_nascimento; }
            set { SetPropertyValue<DateTime>(nameof(mem_data_nascimento), ref fmem_data_nascimento, value); }
        }
        string fmem_telefone;
        [Size(50)]
        public string mem_telefone
        {
            get { return fmem_telefone; }
            set { SetPropertyValue<string>(nameof(mem_telefone), ref fmem_telefone, value); }
        }
        string fmem_email;
        [Size(50)]
        public string mem_email
        {
            get { return fmem_email; }
            set { SetPropertyValue<string>(nameof(mem_email), ref fmem_email, value); }
        }
        string fmem_rua;
        [Size(50)]
        public string mem_rua
        {
            get { return fmem_rua; }
            set { SetPropertyValue<string>(nameof(mem_rua), ref fmem_rua, value); }
        }
        string fmem_bairro;
        [Size(50)]
        public string mem_bairro
        {
            get { return fmem_bairro; }
            set { SetPropertyValue<string>(nameof(mem_bairro), ref fmem_bairro, value); }
        }
        string fmem_numero;
        [Size(50)]
        public string mem_numero
        {
            get { return fmem_numero; }
            set { SetPropertyValue<string>(nameof(mem_numero), ref fmem_numero, value); }
        }
        string fmem_cidade;
        [Size(50)]
        public string mem_cidade
        {
            get { return fmem_cidade; }
            set { SetPropertyValue<string>(nameof(mem_cidade), ref fmem_cidade, value); }
        }
        string fmem_estado;
        [Size(50)]
        public string mem_estado
        {
            get { return fmem_estado; }
            set { SetPropertyValue<string>(nameof(mem_estado), ref fmem_estado, value); }
        }
        string fmem_cep;
        [Size(50)]
        public string mem_cep
        {
            get { return fmem_cep; }
            set { SetPropertyValue<string>(nameof(mem_cep), ref fmem_cep, value); }
        }
        [Association(@"tb_dizimosXPOReferencestb_membrosXPO")]
        public XPCollection<tb_dizimosXPO> tb_dizimoss { get { return GetCollection<tb_dizimosXPO>(nameof(tb_dizimoss)); } }
    }

}
