//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace IpgaSystem.XPO.IpgaDB
{

    [Persistent(@"tb_ministerios")]
    public partial class tb_ministeriosXPO : XPLiteObject
    {
        int fmin_id;
        [Key(true)]
        public int min_id
        {
            get { return fmin_id; }
            set { SetPropertyValue<int>(nameof(min_id), ref fmin_id, value); }
        }
        string fmin_nome;
        [Size(50)]
        public string min_nome
        {
            get { return fmin_nome; }
            set { SetPropertyValue<string>(nameof(min_nome), ref fmin_nome, value); }
        }
        string fmin_descricao;
        [Size(250)]
        public string min_descricao
        {
            get { return fmin_descricao; }
            set { SetPropertyValue<string>(nameof(min_descricao), ref fmin_descricao, value); }
        }
        DateTime fmin_data_criacao;
        public DateTime min_data_criacao
        {
            get { return fmin_data_criacao; }
            set { SetPropertyValue<DateTime>(nameof(min_data_criacao), ref fmin_data_criacao, value); }
        }
        [Association(@"tb_membrosXPOReferencestb_ministeriosXPO")]
        public XPCollection<tb_membrosXPO> tb_membross { get { return GetCollection<tb_membrosXPO>(nameof(tb_membross)); } }
    }

}
