//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace IpgaSystem.XPO.IpgaDB
{

    [Persistent(@"tb_nivel_acesso")]
    public partial class tb_nivel_acessoXPO : XPLiteObject
    {
        int fniv_id;
        [Key(true)]
        public int niv_id
        {
            get { return fniv_id; }
            set { SetPropertyValue<int>(nameof(niv_id), ref fniv_id, value); }
        }
        string fniv_descricao;
        [Size(50)]
        public string niv_descricao
        {
            get { return fniv_descricao; }
            set { SetPropertyValue<string>(nameof(niv_descricao), ref fniv_descricao, value); }
        }
        DateTime fniv_data;
        public DateTime niv_data
        {
            get { return fniv_data; }
            set { SetPropertyValue<DateTime>(nameof(niv_data), ref fniv_data, value); }
        }
        int fniv_nivel_acesso;
        public int niv_nivel_acesso
        {
            get { return fniv_nivel_acesso; }
            set { SetPropertyValue<int>(nameof(niv_nivel_acesso), ref fniv_nivel_acesso, value); }
        }
        [Association(@"tb_usuariosXPOReferencestb_nivel_acessoXPO")]
        public XPCollection<tb_usuariosXPO> tb_usuarioss { get { return GetCollection<tb_usuariosXPO>(nameof(tb_usuarioss)); } }
    }

}
