//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace IpgaSystem.XPO.IpgaDB
{

    [Persistent(@"tb_ofertas")]
    public partial class tb_ofertasXPO : XPLiteObject
    {
        int fofe_id;
        [Key(true)]
        public int ofe_id
        {
            get { return fofe_id; }
            set { SetPropertyValue<int>(nameof(ofe_id), ref fofe_id, value); }
        }
        DateTime fofe_data;
        public DateTime ofe_data
        {
            get { return fofe_data; }
            set { SetPropertyValue<DateTime>(nameof(ofe_data), ref fofe_data, value); }
        }
        string fofe_tipo_ferta;
        [Size(50)]
        public string ofe_tipo_ferta
        {
            get { return fofe_tipo_ferta; }
            set { SetPropertyValue<string>(nameof(ofe_tipo_ferta), ref fofe_tipo_ferta, value); }
        }
    }

}
