//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace IpgaSystem.XPO.IpgaDB
{

    [Persistent(@"tb_usuarios")]
    public partial class tb_usuariosXPO : XPLiteObject
    {
        int fusu_id;
        [Key(true)]
        public int usu_id
        {
            get { return fusu_id; }
            set { SetPropertyValue<int>(nameof(usu_id), ref fusu_id, value); }
        }
        string fusu_nome;
        [Size(50)]
        public string usu_nome
        {
            get { return fusu_nome; }
            set { SetPropertyValue<string>(nameof(usu_nome), ref fusu_nome, value); }
        }
        string fuso_login;
        [Size(50)]
        public string uso_login
        {
            get { return fuso_login; }
            set { SetPropertyValue<string>(nameof(uso_login), ref fuso_login, value); }
        }
        string fuso_nome;
        [Size(50)]
        public string uso_nome
        {
            get { return fuso_nome; }
            set { SetPropertyValue<string>(nameof(uso_nome), ref fuso_nome, value); }
        }
        tb_nivel_acessoXPO fuso_fk_niv_id;
        [Association(@"tb_usuariosXPOReferencestb_nivel_acessoXPO")]
        public tb_nivel_acessoXPO uso_fk_niv_id
        {
            get { return fuso_fk_niv_id; }
            set { SetPropertyValue<tb_nivel_acessoXPO>(nameof(uso_fk_niv_id), ref fuso_fk_niv_id, value); }
        }
        DateTime fuso_data;
        public DateTime uso_data
        {
            get { return fuso_data; }
            set { SetPropertyValue<DateTime>(nameof(uso_data), ref fuso_data, value); }
        }
    }

}
